name: miniproject-pipeleines
on: 
  push: 
    branches: 
      - production
jobs:
  deployment:
    name: deployment-job
    runs-on: ubuntu-latest
    environment: 
      name: sertification_project_IV
    steps:
      - name: checkout code
        uses: actions/checkout@v1 

      - name: set up node environment
        uses: actions/setup-node@v4.0.2

      - name: installing server dependecies
        run: yarn
        working-directory: ./server

      - name: run server tests
        run: yarn test
        working-directory: ./server
        env: 
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGO_URL_TEST: ${{ secrets.MONGO_URL_TEST }}

      - name: installing client dependecies
        run: yarn
        working-directory: ./client
        
      - name: run client tests
        run: yarn test
        working-directory: ./client
        
      - name: build client code
        run: yarn build
        working-directory: ./client
